import { GEM_INFO, GEM_TYPES } from '../constants.js';
import { escapeHtml, gemClass, gemIconElement, gemIconMarkup, renderNobleCost } from './view-helpers.js';

function node(tag, className = '', text = '') { const element = document.createElement(tag); if (className) element.className = className; if (text) element.textContent = text; return element; }
function heading(kicker, title, id) { const wrap = node('div'); wrap.append(node('p', 'section-kicker', kicker), node('h2', '', title)); if (id) wrap.lastElementChild.id = id; return wrap; }

export function createActionPanel() {
  const section = node('section', 'action-panel'); section.setAttribute('aria-labelledby', 'actions-title');
  const header = node('div', 'section-heading compact'); header.append(heading('YOUR MOVE', '主要行动', 'actions-title'));
  const buttons = node('div', 'action-buttons'); buttons.id = 'action-buttons';
  const specs = [['take-different', ['white', 'blue', 'green'], '拿取宝石', '选择不同颜色'], ['take-same', ['white', 'white'], '同色双取', '库存至少四枚'], ['buy', [], '购买卡牌', '从市场或预留区'], ['reserve', ['gold'], '预定卡牌', '最多三张并可能获得黄金']];
  for (const [intent, gems, label, hint] of specs) { const button = node('button', 'action-button'); button.type = 'button'; button.dataset.intent = intent; button.setAttribute('aria-pressed', 'false'); const icon = node('span', 'action-gem-icons'); gems.forEach((gem) => icon.append(gemIconElement(gem, 'action-gem-icon'))); if (!gems.length) icon.textContent = '▣'; button.append(icon, node('strong', '', label), node('small', '', hint)); buttons.append(button); }
  const controls = node('div', 'selection-controls'); controls.id = 'selection-controls'; controls.hidden = true; controls.append(node('p', '', '')); controls.lastElementChild.id = 'selection-summary';
  const actions = node('div'); const cancel = node('button', 'button button-quiet', '取消'); cancel.type = 'button'; cancel.dataset.command = 'cancel-intent'; const confirm = node('button', 'button button-primary', '确认'); confirm.type = 'button'; confirm.id = 'confirm-selection'; confirm.dataset.command = 'confirm-selection'; actions.append(cancel, confirm); controls.append(actions);
  section.append(header, buttons, controls); return section;
}

export function createGameLog() { const section = node('section', 'log-panel'); section.setAttribute('aria-labelledby', 'log-title'); const header = node('div', 'section-heading compact'); header.append(heading('LEDGER', '行动账簿', 'log-title')); const snapshots = node('span', 'snapshot-count'); snapshots.id = 'snapshot-count'; header.append(snapshots); const list = node('ol', 'action-log'); list.id = 'action-log'; section.append(header, list); return section; }
export function createPlayerPanel() { const section = node('section', 'player-panel'); section.id = 'player-panel'; section.setAttribute('aria-labelledby', 'player-panel-title'); return section; }
export function createMarket() { const market = node('div', 'market-grid'); market.id = 'market'; return market; }
export function createGemBank() { const bank = node('div', 'gem-bank'); bank.id = 'token-pool'; bank.setAttribute('aria-label', '公共宝石银行'); return bank; }

export function createNobleElement(noble, { legal = false, selected = false } = {}) {
  const button = node('button', `noble-card ${legal ? 'is-legal' : ''} ${selected ? 'is-selected' : ''}`); button.type = 'button'; button.dataset.nobleId = noble.id; button.disabled = !legal;
  button.setAttribute('aria-label', `${noble.points} 分贵族，条件：${Object.entries(noble.cost).filter(([, count]) => count).map(([gem, count]) => `${GEM_INFO[gem].name}${count}`).join('、')}`); button.setAttribute('aria-selected', String(selected));
  button.innerHTML = `<span class="noble-portrait" aria-hidden="true">♛</span><strong>★ ${noble.points}</strong><span class="noble-cost">${renderNobleCost(noble)}</span>`; return button;
}

export function createDeckElement(level, count, actionable) { const deck = node('button', `deck-card tier-${level} ${actionable ? 'is-reservable' : ''}`); deck.type = 'button'; deck.dataset.deckLevel = String(level); deck.disabled = !actionable; deck.setAttribute('aria-label', `预定一张 ${level} 级牌堆顶卡，剩余 ${count} 张`); deck.innerHTML = `<span class="deck-pattern" aria-hidden="true">◆</span><strong>${level} 级</strong><small>余 ${count} 张</small>`; return deck; }

export function createCardElement(card, { source = 'market', index = 0, legalBuy = false, legalReserve = false, selected = false } = {}) {
  const classes = ['development-card', `tier-${card.level}`, gemClass(card.bonus), card.points ? 'has-points' : 'no-points']; if (legalBuy) classes.push('is-affordable', 'is-legal'); if (legalReserve) classes.push('is-reservable', 'is-legal'); if (selected) classes.push('is-selected');
  const button = node('button', classes.join(' ')); button.type = 'button'; button.dataset.cardSource = source; button.dataset.cardLevel = String(card.level); button.dataset.cardIndex = String(index); button.disabled = !legalBuy && !legalReserve; button.setAttribute('aria-selected', String(selected)); button.setAttribute('aria-label', `${source === 'market' ? '市场' : '预留'} ${card.level} 级卡，${card.points} 声望，${GEM_INFO[card.bonus].name}永久折扣${legalBuy ? '，可购买' : ''}${legalReserve ? '，可预定' : ''}`);
  const cost = GEM_TYPES.filter((gem) => card.cost[gem] > 0).map((gem) => `<span class="cost-chip ${gemClass(gem)}"><strong>${card.cost[gem]}</strong>${gemIconMarkup(gem, 'cost-gem-icon')}</span>`).join('');
  button.innerHTML = `<span class="card-tier">${card.level} 级</span><span class="card-head"><span class="card-points">${card.points ? String(card.points) : ''}</span><span class="card-bonus">${gemIconMarkup(card.bonus, 'card-bonus-icon')}</span></span><span class="card-art card-art-${escapeHtml(card.bonus)}" aria-hidden="true">${gemIconMarkup(card.bonus, 'card-art-icon')}</span><span class="card-cost">${cost}</span>`; return button;
}

export function createReservedCardElement(card, options) { const cardElement = createCardElement(card, { ...options, source: 'reserved' }); cardElement.classList.add('reserved-card'); return cardElement; }
export function createGemToken(gem, count, { selectable = false, selectedCount = 0 } = {}) { const info = GEM_INFO[gem]; const token = node('button', `token token-stack ${gemClass(gem)} ${selectable ? 'is-legal' : ''} ${selectedCount ? 'is-selected' : ''}`); token.type = 'button'; token.dataset.gem = gem; token.disabled = !selectable; token.setAttribute('aria-label', `${info.name}，银行剩余 ${count}${selectedCount ? `，已选择 ${selectedCount} 枚` : ''}`); token.setAttribute('aria-pressed', String(selectedCount > 0)); const stack = node('span', 'gem-discs'); stack.style.setProperty('--stack-depth', String(Math.min(5, Math.ceil(count / 2)))); stack.append(gemIconElement(gem, 'token-gem-icon')); token.append(stack, node('strong', 'token-count', String(count)), node('span', 'token-name', `${info.name}${selectedCount ? ` · ${selectedCount}` : ''}`)); return token; }

export function createBoard() {
  const game = document.getElementById('game'); if (game.dataset.boardReady === 'true') return game; game.replaceChildren(); game.dataset.boardReady = 'true';
  const topbar = node('header', 'topbar game-statusbar'); const identity = node('div'); identity.append(node('p', 'eyebrow', 'THE GEM MERCHANT'), node('h1', '', '宝石商人')); identity.lastElementChild.id = 'game-title'; const status = node('div', 'topbar-actions'); const version = node('span', 'version-badge'); version.id = 'version-badge'; const exportButton = node('button', 'button button-quiet', '导出存档'); exportButton.type = 'button'; exportButton.dataset.command = 'export'; const importLabel = node('label', 'button button-quiet file-button', '导入存档'); const input = node('input'); input.id = 'import-file'; input.type = 'file'; input.accept = 'application/json,.json'; importLabel.append(input); const newGame = node('button', 'button button-quiet', '新对局'); newGame.type = 'button'; newGame.dataset.command = 'new-game'; status.append(version, exportButton, importLabel, newGame); topbar.append(identity, status);
  const table = node('div', 'table-layout'); const nobles = node('section', 'board-section noble-section table-nobles'); nobles.append(heading('PATRONS', '贵族议会', 'nobles-title'), node('div', 'nobles-row')); nobles.lastElementChild.id = 'nobles'; const market = node('section', 'board-section market-section table-market'); const marketHead = node('div', 'section-heading'); marketHead.append(heading('DEVELOPMENTS', '发展卡市场', 'market-title'), node('p', '', '选择一张卡牌查看操作')); marketHead.lastElementChild.id = 'market-hint'; market.append(marketHead, createMarket()); const bank = node('section', 'board-section bank-section table-bank'); bank.append(heading('TREASURY', '公共宝石银行', 'tokens-title'), createGemBank()); const playerSidebar = node('aside', 'player-sidebar'); playerSidebar.setAttribute('aria-label', '玩家状态栏'); const sidebarTitle = node('div', 'player-sidebar-heading'); sidebarTitle.append(node('p', 'section-kicker', 'MERCHANTS'), node('h2', '', '玩家状态')); const opponents = node('div', 'player-status-list'); opponents.id = 'opponents'; playerSidebar.append(sidebarTitle, opponents); table.append(nobles, market, bank, playerSidebar);
  const bottom = node('div', 'bottom-layout'); bottom.append(createPlayerPanel(), createActionPanel(), createGameLog()); game.append(topbar, table, bottom); return game;
}
